# Generated by Django 4.2.5 on 2023-10-12 15:42

from django.db import migrations, models
import sylAnalyzer.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFileForm', models.FileField(upload_to='uploads/', validators=[sylAnalyzer.validators.validate_file_extension])),
            ],
        ),
    ]
