# Generated by Django 4.2.5 on 2023-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileForm',
            new_name='UploadFileModel',
        ),
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='uploadFileForm',
            new_name='uploadFileModel',
        ),
    ]
