# Generated by Django 4.2.5 on 2023-10-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylAnalyzer', '0002_rename_uploadfileform_uploadfilemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='uploadFileModel',
            new_name='file',
        ),
    ]
